# rule_key: quantum.arq-q-0948-config
# evidence_anchor: sslEnabledProtocols
# regex_sample: sslEnabledProtocolsw6S iX[JB ])*+a|6&IBC `TLSv1.1
# keywords: sslEnabledProtocols | TLSv1 | TLSv1.1
<Connector sslEnabledProtocols="TLSv1,TLSv1.1" />
